version: '2'
services:
  mysqld-exporter:
    image: registry.drycc.cc/drycc-addons/mysqld-exporter:0.14.0
    ports:
      - 9104:9104
    environment:
      - DATA_SOURCE_NAME='dbuser:dbpassword@(dbhost:3306)/'